services:
  postgres:
    image: 'postgres:latest'
    container_name: "StockManager_Container"
    environment:
      - 'POSTGRES_DB=stockmanagerdb'
      - 'POSTGRES_PASSWORD=verysecret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    restart: on-failure
